# Generated by Django 4.2.6 on 2023-10-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0002_news_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
        migrations.AlterModelTable(
            name='news_category',
            table='News_category',
        ),
    ]
